export const CAN_MUTATE_USER = "CAN_MUTATE_USER";
export const CAN_MUTATE_PATIENT = "CAN_MUTATE_PATIENT";
export const CAN_ADD_TEST = "CAN_ADD_TEST";
export const CAN_VIEW_TEST = "CAN_VIEW_TEST";
export const CAN_EDIT_TEST = "CAN_EDIT_TEST";
export const CAN_DELETE_TEST = "CAN_DELETE_TEST";
export const CAN_MUTATE_USER_REPORT = "CAN_MUTATE_USER_REPORT";
